version: '3'
services:
  wp:
    image: wordpress
    deploy:
      replicas: 3
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_TABLE_PREFIX: wp1_
    ports:
      - "8989:80"
  db:
    image: mysql:5.7
    deploy:
      replicas: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpdb
    volumes:
      - "nfsvolume:/nfsdata"
volumes:
  nfsvolume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.31.82.171,vers=4,soft,timeo=180,bg,tcp,rw"
      device: "172.31.82.171:/home/ubuntu/nfsvata"
